#!/bin/bash

# Test
bun run test

# Formatting
biome check --fix --files-ignore-unknown=true --formatter-enabled=true --assist-enabled=true  --linter-enabled=false --config-path=biome.json $(git diff --cached --name-only --diff-filter=AMCR | sed 's| |\\ |g')
git update-index --again

# Linting
bun run lint